'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';

export default function Hero() {
  const reduceMotion = useReducedMotion();
  return <section className="dream-hero" id="home"><div className="hero-glow glow-a" /><div className="hero-glow glow-b" /><div className="pixel-spark spark-a">✦</div><div className="pixel-spark spark-b">♡</div><div className="pixel-spark spark-c">✳</div><motion.div className="hero-copy" initial={reduceMotion ? false : { y: 22 }} animate={{ y: 0 }} transition={{ duration: .7 }}><p className="pink-kicker"><span>✦</span> A LITTLE CAFÉ WITH A LOT OF HEART <span>✦</span></p><h1>A Little Scoop<br />of <em>Happiness.</em></h1><p className="hero-subtitle">Waffles, shakes, and slow sips in a corner made for good company.</p><div className="hero-buttons"><Link className="pink-pill" href="#menu">Explore Our Menu <span>↗</span></Link><Link className="outline-pill" href="#contact">Find Your Happy Place <span>♡</span></Link></div><div className="hero-chips"><span>✿ sweet treats</span><span>☁ cozy moments</span><span>♡ made with love</span></div></motion.div><motion.div className="hero-logo-wrap hero-collage" initial={reduceMotion ? false : { y: 20 }} animate={{ y: 0 }} transition={{ duration: .8, delay: .12 }}><div className="hero-photo-backdrop" /><figure className="hero-photo hero-photo-main"><Image src="/cafe-gallery/WhatsApp Image 2026-09-27 at 3.34.22 PM (1).jpeg" alt="Cozy pink seating beneath an illuminated arch at Scoop N Brew" fill priority sizes="(max-width: 760px) 82vw, 34vw" className="hero-photo-img" /><figcaption>THE COZIEST CORNER <span>♡</span></figcaption></figure><figure className="hero-photo hero-photo-small"><Image src="/cafe-gallery/WhatsApp Image 2026-09-27 at 3.34.20 PM.jpeg" alt="Playful ice cream art on the café's pink brick wall" fill sizes="(max-width: 760px) 38vw, 15vw" className="hero-photo-img" /></figure><motion.div className="hero-logo-card" animate={reduceMotion ? undefined : { y: [0, -7, 0], rotate: [7, 9, 7] }} transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}><Image src="/logo.jpeg" alt="Scoop N Brew logo" width={420} height={420} priority className="hero-logo" /></motion.div><span className="hero-sticker sticker-top">SWEET<br />SPOT ✦</span><span className="hero-sticker sticker-bottom">11 AM<br />— 10 PM</span><span className="collage-doodle doodle-heart">♡</span><span className="collage-doodle doodle-star">✳</span></motion.div><div className="hero-bottom-note"><span>SCROLL FOR A LITTLE JOY</span><span className="scroll-line" /></div></section>;
}
